spring.application.name=serviceregistry


spring.config.import=optional:configserver:http://localhost:8071

#actuator
management.endpoints.web.exposure.include=*
management.health.readiness-state.enabled=true
management.health.liveness-state.enabled=true
management.endpoint.health.probes.enabled=true

#metrics
management.metrics.tags.application=${spring.application.name}

#distributed tracing
logging.pattern.level= %5p[${spring.application.name:-},%X{trace_id:-},%X{span_id:-}]