global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'department-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['department-service:8080']

  - job_name: 'organization-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['organization-service:8083']

  - job_name: 'employee-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['employee-service:8081']

  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8072']

  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-registry:8070']

  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['config-server:8071']
