spring.application.name=gatewayserver

#automatically redirect the req to the services
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#config server
spring.config.import=optional:configserver:http://localhost:8071

#actuator
management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true

#metrics
management.metrics.tags.application=${spring.application.name}

info.app.name=gateway
info.app.description=gateway service
info.app.version=1.0.0

logging.level.com.apigateway=DEBUG
logging.pattern.level= %5p[${spring.application.name:-},%X{trace_id:-},%X{span_id:-}]

#circuit breaker pattern
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10000

#timeout config for entire application
spring.cloud.gateway.httpclient.connect-timeout=1000
spring.cloud.gateway.httpclient.response-timeout=10s

#rate limiter
spring.data.redis.connect-timeout=2s
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=1s

#OAuth
#This is the Keycloak endpoint that exposes the JSON Web Key Set used to validate JWT signatures.
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:7080/realms/master/protocol/openid-connect/certs


