services:
  network-deploy-service:
    networks:
      - msDocker

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    healthcheck:
      test: "curl --fail --silent http://localhost:$$SERVER_PORT/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    depends_on:
      service-registry:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8070/eureka/

