spring.application.name=employee
server.port=8081
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/employee
spring.datasource.username=root
spring.datasource.password=TM@rootuser
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

department.service.url=${DEPARTMENT_SERVICE_URL:http://localhost:8080}
organization.service.url=${ORGANIZATION_SERVICE_URL:http://localhost:8083}


spring.profiles.active=prod

#define the link for the config server note we need to define the spring.application.name
spring.config.import=optional:configserver:http://localhost:8071

# actuator
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
management.endpoint.shutdown.enabled=true

# health checks
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.liveness-state.enabled=true
management.health.readiness-state.enabled=true

#metrics
management.metrics.tags.application=${spring.application.name}

#service registry and discovery

eureka.instance.preferIpAddress=True
eureka.client.service-url.defaultZone=http://localhost:8070/eureka

info.app.name=employee
info.app.description=employee service
info.app.version=1.0.0

logging.level.com.employee_service=DEBUG

#distributed tracing
logging.pattern.level= %5p[${spring.application.name:-},%X{trace_id:-},%X{span_id:-}]

spring.cloud.openfeign.circuitbreaker.enabled=True

#circuit breaker pattern
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10000

#retry
resilience4j.retry.configs.default.maxRetryAttempts=4
resilience4j.retry.configs.default.waitDuration=2s
resilience4j.retry.configs.default.retryExceptions=java.util.concurrent.TimeoutException

# Input binding ? consumes from queue 'communication-sent'
spring.cloud.function.definition=updateCommunication
spring.cloud.stream.bindings.updateCommunication-in-0.destination=communication-sent
spring.cloud.stream.bindings.updateCommunication-in-0.group=${spring.application.name}

# Output binding ? produces to queue 'send-communication'
spring.cloud.stream.bindings.sendCommunication-out-0.destination=send-communication



spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.connection-timeout:10s